services:
  osrm:
    image: osrm/osrm-backend
    volumes:
      - ~/Documents/osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/singapore.osm.pbf && 
      osrm-partition /data/singapore.osrm && 
      osrm-customize /data/singapore.osrm && 
      osrm-routed --algorithm mld /data/singapore.osrm
      "
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge