services:
  postgis:
    image: "postgis/postgis"
    environment:
      - POSTGRES_DB=gpx
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: arbatovevgeny@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - default
    ports:
      - "80:80"
    depends_on:
      - postgis
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  osrm:
    image: osrm/osrm-backend
    container_name: "route-gen-osrm"
    volumes:
      - ~/Documents/osm:/data
      - ./osrm/profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: bash -c "osrm-extract -l INFO -p /profiles/foot.lua /data/singapore.osm.pbf && osrm-partition -l INFO /data/singapore.osrm && osrm-customize -l INFO /data/singapore.osrm && osrm-routed -l INFO --algorithm mld /data/singapore.osrm"
  # ui:
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   container_name: "route-gen-ui"
  #   ports:
  #     - 80:80
  #   networks:
  #     - default
  #   restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  pgadmin-data: